#       ImageId: ami-0729e439b6769d6ab , ami-0c4f7023847b90238, ami-0c4f7023847b90238 (22.04)

Description: >
  UdaPeople backend stack.

Parameters:
  ID:
    Description: Unique identifier.
    Type: String

Resources:
  InstanceSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub UdaPeople-${ID}
      GroupDescription: Allow port 22 and port 3030.
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 3030
          ToPort: 3030
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 9100
          ToPort: 9100
          CidrIp: 0.0.0.0/0

        # - IpProtocol: tcp
        #   FromPort: 5432
        #   ToPort: 5432
        #   CidrIp: 0.0.0.0/0
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      SecurityGroups:
        - Ref: InstanceSecurityGroup
      KeyName: udacity # auto-deploy-keypair   If you use another key pair name, you should change this value to match.
      # If this ami id is not available for you, you can find another (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/finding-an-ami.html)
      # Ubuntu 18 or higher works fine ami-08d4ac5b634553e16   ami-0c4f7023847b90238 
      # ami-08d4ac5b634553e16    ami-0729e439b6769d6ab (18.04)    ami-08d4ac5b634553e16 (20.04)
      # ami-052efd3df9dad4825 (22.04) ami-0c4f7023847b90238 ubuntu/images/hvm-ssd/ubuntu-focal-20.04-amd64-server-20220419
      ImageId:  ami-0729e439b6769d6ab
       
      Tags:
        - Key: Name
          Value: !Sub backend-${ID}
